# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
