# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
