# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_auto_20160413_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='about',
            field=models.TextField(default='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='example@example.net', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.URLField(default='www.terra.com.br'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
