# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_auto_20160415_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default='sql'),
            preserve_default=False,
        ),
    ]
