# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
