# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_auto_20160415_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug-test', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
