# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0009_auto_20160416_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
